version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_papillon
    environment:
      POSTGRES_DB: papillon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - papillon_net

  app:
    build: .
    container_name: spring_papillon
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/papillon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - papillon_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - papillon_net
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  db_data:

networks:
  papillon_net: